version: "3"
services:
  app:
    container_name: "next"
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    links:
      - database
  database:
    container_name: database
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
